### ISSUE TITLE
FileNotFoundError('can not find executors.py')

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/executor-clip-image#20]
Using the [hub-migrate branch of my image search](https://github.com/alexcg1/jina-meme-search-image-backend/tree/hub-migrate):

### Using CLIP image encoder (and some other encoders):

Run: `python app.py -t index -n 10`

Output:

```
clip_encoder@17[E]:FileNotFoundError('can not find executors.py') during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
```

Full output attached at end of issue

### Flow code

```yaml
...
executors:
...
  - name: clip_encoder
    uses: 'jinahub+docker://CLIPImageEncoder:v1'
    volumes: './cache/clip:/root/.cache/clip'
---
```

### Notes

It works fine using BIT image encoder from Hub. But some other executors (Image Normalizer, CLIP, maybe more) present the error above.

### Log

Seems I can't attach files, so here's the output instead:

```
/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/importer.py:136: UserWarning: 
                executors shadows one of built-in Python module name.
                It is imported as `jinahub.executors`
                
                Affects:
                - Either, change your code from using `from executors import ...` to `from jinahub.executors import ...`
                - Or, rename executors to another name
                
  warnings.warn(
/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/importer.py:136: UserWarning: 
                executors shadows one of built-in Python module name.
                It is imported as `jinahub.executors`
                
                Affects:
                - Either, change your code from using `from executors import ...` to `from jinahub.executors import ...`
                - Or, rename executors to another name
                
  warnings.warn(
/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/importer.py:136: UserWarning: 
                executors shadows one of built-in Python module name.
                It is imported as `jinahub.executors`
                
                Affects:
                - Either, change your code from using `from executors import ...` to `from jinahub.executors import ...`
                - Or, rename executors to another name
                
  warnings.warn(
        crafter@56485[I]:ready and listening
/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/importer.py:136: UserWarning: 
                executors shadows one of built-in Python module name.
                It is imported as `jinahub.executors`
                
                Affects:
                - Either, change your code from using `from executors import ...` to `from jinahub.executors import ...`
                - Or, rename executors to another name
                
  warnings.warn(
   clip_encoder@56498[I]:
   clip_encoder@56498[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
   clip_encoder@56498[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
   clip_encoder@56498[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
   clip_encoder@56498[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
   clip_encoder@56498[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
   clip_encoder@56498[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
   clip_encoder@56498[I]:MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
   clip_encoder@56498[I]:NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
   clip_encoder@56498[I]:KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   clip_encoder@56498[I]:
   clip_encoder@56498[I]:▶️  /usr/local/bin/jina executor --uses config.yml --name clip_encoder --workspace /mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/workspace --identity d098cfb6-f2cf-436d-af22-c15ba0ef4178 --workspace-id b80fe088-caf8-4242-90e9-c3dbd600b876 --zmq-identity bd407b40-0af3-460c-b259-7c59dcbab8b7 --port-ctrl 48581 --py-modules executors.py --port-in 46989 --port-out 33247 --hosts-in-connect --socket-in ROUTER_BIND --socket-out ROUTER_BIND --num-part 1 --dynamic-routing-out --dynamic-routing-in --port-expose 48927 --upload-files executors.py --noblock-on-start
   clip_encoder@56498[I]:🔧️                            cli = executor                      
   clip_encoder@56498[I]:ctrl-with-ipc = False
   clip_encoder@56498[I]:daemon = False
   clip_encoder@56498[I]:disable-remote = False
   clip_encoder@56498[I]:docker-kwargs = None
   clip_encoder@56498[I]:dynamic-routing = True
   clip_encoder@56498[I]:🔧️             dynamic-routing-in = True                          
   clip_encoder@56498[I]:🔧️            dynamic-routing-out = True                          
   clip_encoder@56498[I]:entrypoint = None
   clip_encoder@56498[I]:env = None
   clip_encoder@56498[I]:expose-public = False
   clip_encoder@56498[I]:external = False
   clip_encoder@56498[I]:host = 0.0.0.0
   clip_encoder@56498[I]:host-in = 0.0.0.0
   clip_encoder@56498[I]:host-out = 0.0.0.0
   clip_encoder@56498[I]:🔧️               hosts-in-connect = []                            
   clip_encoder@56498[I]:🔧️                       identity = d098cfb6-f2cf-436d-af22-c15ba0
   clip_encoder@56498[I]:log-config = /usr/local/lib/python3.7/site-
   clip_encoder@56498[I]:memory-hwm = -1
   clip_encoder@56498[I]:🔧️                           name = clip_encoder                  
   clip_encoder@56498[I]:🔧️               noblock-on-start = True                          
   clip_encoder@56498[I]:🔧️                       num-part = 1                             
   clip_encoder@56498[I]:on-error-strategy = IGNORE
   clip_encoder@56498[I]:override-metas = None
   clip_encoder@56498[I]:override-with = None
   clip_encoder@56498[I]:parallel = 1
   clip_encoder@56498[I]:pea-id = 0
   clip_encoder@56498[I]:pea-role = SINGLETON
   clip_encoder@56498[I]:peas-hosts = None
   clip_encoder@56498[I]:pod-role = None
   clip_encoder@56498[I]:polling = ANY
   clip_encoder@56498[I]:🔧️                      port-ctrl = 48581                         
   clip_encoder@56498[I]:🔧️                    port-expose = 48927                         
   clip_encoder@56498[I]:🔧️                        port-in = 46989                         
   clip_encoder@56498[I]:🔧️                       port-out = 33247                         
   clip_encoder@56498[I]:proxy = False
   clip_encoder@56498[I]:pull-latest = False
   clip_encoder@56498[I]:🔧️                     py-modules = ['executors.py']              
   clip_encoder@56498[I]:quiet = False
   clip_encoder@56498[I]:quiet-error = False
   clip_encoder@56498[I]:quiet-remote-logs = False
   clip_encoder@56498[I]:replicas = 1
   clip_encoder@56498[I]:runs-in-docker = False
   clip_encoder@56498[I]:runtime-backend = PROCESS
   clip_encoder@56498[I]:runtime-cls = ZEDRuntime
   clip_encoder@56498[I]:scheduling = LOAD_BALANCE
   clip_encoder@56498[I]:🔧️                      socket-in = ROUTER_BIND                   
   clip_encoder@56498[I]:🔧️                     socket-out = ROUTER_BIND                   
   clip_encoder@56498[I]:ssh-keyfile = None
   clip_encoder@56498[I]:ssh-password = None
   clip_encoder@56498[I]:ssh-server = None
   clip_encoder@56498[I]:timeout-ctrl = 5000
   clip_encoder@56498[I]:timeout-ready = 600000
   clip_encoder@56498[I]:🔧️                   upload-files = ['executors.py']              
   clip_encoder@56498[I]:🔧️                           uses = config.yml                    
   clip_encoder@56498[I]:uses-after = None
   clip_encoder@56498[I]:uses-before = None
   clip_encoder@56498[I]:volumes = None
   clip_encoder@56498[I]:🔧️                      workspace = /mnt/data/work/repos/personal/
   clip_encoder@56498[I]:🔧️                   workspace-id = b80fe088-caf8-4242-90e9-c3dbd6
   clip_encoder@56498[I]:🔧️                   zmq-identity = bd407b40-0af3-460c-b259-7c59dc
   clip_encoder@56498[I]:
   clip_encoder@56498[I]:   clip_encoder@17[E]:FileNotFoundError('can not find executors.py') during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
   clip_encoder@56498[I]:add "--quiet-error" to suppress the exception details
   clip_encoder@56498[I]:Traceback (most recent call last):
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 164, in run
   clip_encoder@56498[I]:runtime = self._build_runtime()
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 150, in _build_runtime
   clip_encoder@56498[I]:self.args, ctrl_addr=ctrl_addr, ready_event=self.is_ready
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 58, in __init__
   clip_encoder@56498[I]:self._load_plugins()
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 111, in _load_plugins
   clip_encoder@56498[I]:PathImporter.add_modules(*self.args.py_modules)
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 111, in add_modules
   clip_encoder@56498[I]:paths = [complete_path(m) for m in paths]
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 111, in <listcomp>
   clip_encoder@56498[I]:paths = [complete_path(m) for m in paths]
   clip_encoder@56498[I]:File "/usr/local/lib/python3.7/site-packages/jina/jaml/helper.py", line 187, in complete_path
   clip_encoder@56498[I]:raise FileNotFoundError(f'can not find {path}')
   clip_encoder@56498[I]:FileNotFoundError: can not find executors.py
   clip_encoder@56498[I]:/usr/local/lib/python3.7/site-packages/jina/helper.py:827: UserWarning: Install `uvloop` via `pip install "jina[uvloop]"` for better performance.
   clip_encoder@56498[I]:'Install `uvloop` via `pip install "jina[uvloop]"` for better performance.'
   clip_encoder@56498[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 157, in run
    runtime = self._build_runtime()
  File "/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 144, in _build_runtime
    return self.runtime_cls(self.args, ctrl_addr=ctrl_addr)
  File "/mnt/data/work/repos/personal/meme-search/jina-meme-search-backend-image/env/lib/python3.8/site-packages/jina/peapods/runtimes/container/__init__.py", line 28, in __init__
    raise Exception(
Exception: the container fails to start, check the arguments or entrypoint
           Flow@56485[E]:clip_encoder:<jina.peapods.pods.Pod object at 0x7f030bc908e0> can not be started due to RuntimeFailToStart(), Flow is aborted

-------------------------------------------------------------------------------
app.py 156 <module>
main()

core.py 829 __call__
return self.main(*args, **kwargs)

core.py 782 main
rv = self.invoke(ctx)

core.py 1066 invoke
return ctx.invoke(self.callback, **ctx.params)

core.py 610 invoke
return callback(*args, **kwargs)

app.py 145 main
index(docs, num_docs)

app.py 102 index
with flow:

base.py 926 __enter__
return self.start()

base.py 971 start
v.wait_start_success()

__init__.py 518 wait_start_success
p.wait_start_success()

__init__.py 214 wait_start_success
raise RuntimeFailToStart

jina.excepts.RuntimeFailToStart
```

### `jina -vf` output

```
- jina 2.0.0
- jina-proto 0.0.84
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.19.5
- protobuf 3.17.3
- proto-backend cpp
- grpcio 1.34.1
- pyyaml 5.4.1
- python 3.8.10
- platform Linux
- platform-release 5.10.42-1-MANJARO
- platform-version #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021
- architecture x86_64
- processor
- uid 242011234364068
- session-id 4383eaa2-df25-11eb-8884-dc1ba1a7eaa4
- uptime 2021-07-07T15:14:30.105883
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
```

**Comment by mapleeit** [comment]
@alexcg1 Did the new Flow which Felix posted work for you?

https://jinaai.slack.com/archives/C0183GCN8AK/p1625666547446500?thread_ts=1625663708.445100&cid=C0183GCN8AK

**Comment by alexcg1** [comment]
> @alexcg1 Did the new Flow which Felix posted work for you?
> 
> https://jinaai.slack.com/archives/C0183GCN8AK/p1625666547446500?thread_ts=1625663708.445100&cid=C0183GCN8AK

Yup, works well both on bare metal and in building Docker image (I removed the `+docker` from the Flow)

**Comment by alexcg1** [comment]
I was working on so many Jina projects yesterday I got confused. Image search isn't working (but app store search is)

**Comment by alexcg1** [comment]
I'll post updated log output soon

**Comment by alexcg1** [comment]
So, it builds and runs perfectly in Docker!

But it doesn't run on bare metal now, even after manually running `jina hub pull jinahub://TransformerTorchEncoder`

#### `python app.py -t index -n 10` output

```
[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;31m        encoder@31815[C]:can not load the executor from /home/alexcg/.jina/hub-packages/u9pqs8eb/config.yml
[0m[0;31m        encoder@31815[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/importer.py", line 148, in _path_import
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alexcg/.jina/hub-packages/u9pqs8eb/transform_encoder.py", line 10, in <module>
    from jina_commons.batching import get_docs_batch_generator
ModuleNotFoundError: No module named 'jina_commons'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 83, in _load_executor
    self._executor = BaseExecutor.load_config(
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/jaml/__init__.py", line 537, in load_config
    load_py_modules(
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/jaml/helper.py", line 241, in load_py_modules
    PathImporter.add_modules(*mod)
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/importer.py", line 118, in add_modules
    module = PathImporter._path_import(p)
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/importer.py", line 150, in _path_import
    raise ImportError(f'can not import module from {absolute_path}') from ex
ImportError: can not import module from /home/alexcg/.jina/hub-packages/u9pqs8eb/transform_encoder.py

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 157, in run
    runtime = self._build_runtime()
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 144, in _build_runtime
    return self.runtime_cls(self.args, ctrl_addr=ctrl_addr)
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 58, in __init__
    self._load_executor()
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 100, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
[0m[1;30m[0m[0;31m           Flow@31804[E]:encoder:<jina.peapods.pods.Pod object at 0x7f6974c96be0> can not be started due to RuntimeFailToStart(), Flow is aborted
[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0m[1;30m[0mTraceback (most recent call last):
  File "app.py", line 84, in <module>
    main()
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "app.py", line 76, in main
    index(num_docs=num_docs)
  File "app.py", line 34, in index
    with flow:
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/flow/base.py", line 926, in __enter__
    return self.start()
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/flow/base.py", line 971, in start
    v.wait_start_success()
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/pods/__init__.py", line 518, in wait_start_success
    p.wait_start_success()
  File "/mnt/data/work/repos/jina-app-store-example-felix/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 214, in wait_start_success
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by alexcg1** [comment]
Seems `jina hub pull` isn't pulling `jina_commons`, even when I run it with `--install-requirements`

**Comment by nan-wang** [comment]
```
    uses: 'jinahub+docker://CLIPImageEncoder:v1'
```
 @alexcg1 Is this issue still valid? If yes, please give it a try to remove the tag, `:v1`.

**Comment by alexcg1** [comment]
> ```
>     uses: 'jinahub+docker://CLIPImageEncoder:v1'
> ```
>  @alexcg1 Is this issue still valid? If yes, please give it a try to remove the tag, `:v1`. 

I'll try today

**Comment by alexcg1** [comment]
I wrote a simpler test program to test this out and it seems to not crash any more:

```python
from jina import Flow, DocumentArray
from jina.types.document.generators import from_files

# Create list of docs to search
docs = DocumentArray(from_files('data/**/*.png'))

# Set up Flow
flow = Flow(protocol='http', port_expose=4352)
flow.add(uses="jinahub+docker://CLIPImageEncoder").add(uses='jinahub+docker://SimpleIndexer')

# Run Flow
with flow:
    # Index files
    flow.index(docs)
    # Keep Flow open
    flow.block()
```

However, I can't get querying to work. It doesn't return any matches. Maybe because I'm not passing the right `uses_with` params. But that's another problem entirely

**Comment by alexcg1** [comment]
Just for reference, the code above doesn't work. Code below is better:

```python
from jina import Flow
from jina.types.document.generators import from_files

# Create list of docs to search
docs = from_files('data/**/*.png')

# Set up Flow
flow = Flow(protocol='http', port_expose=4352).add(uses="jinahub+docker://CLIPImageEncoder").add(uses='jinahub+docker://SimpleIndexer')

# Run Flow
with flow:
    # Index files
    flow.post(on="/index", inputs=docs)
    # Keep Flow open
    flow.block()
```
